/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // Alat untuk mengatur isi tabel
import java.util.Vector; // Wadah sementara untuk menampung satu baris data
import java.sql.PreparedStatement;
/**
 *
 * @author ASUS
 */
public class ForAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForAdmin.class.getName());

    /**
     * Creates new form ForAdmin
     */
    public ForAdmin() {
        initComponents();
        tampilkanData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLaporan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIDAdmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaAdmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsiAdmin = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cmbStatusAdmin = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar Laporan Masuk");

        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelLaporanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelLaporan);

        jLabel2.setText("ID Laporan");

        txtIDAdmin.setEditable(false);
        txtIDAdmin.setBackground(new java.awt.Color(255, 255, 255));
        txtIDAdmin.addActionListener(this::txtIDAdminActionPerformed);

        jLabel3.setText("Nama Pelapor");

        jLabel4.setText("Deskripsi");

        txtDeskripsiAdmin.setColumns(20);
        txtDeskripsiAdmin.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsiAdmin);

        jLabel5.setText("Update Status");

        cmbStatusAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Sedang Dikerjakan", "Selesai" }));

        btnUpdate.setBackground(new java.awt.Color(102, 255, 102));
        btnUpdate.setText("Update Data");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        jLabel6.setText("Cari Data (Nama/Deskripsi):");

        txtCari.addActionListener(this::txtCariActionPerformed);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtIDAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(txtNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbStatusAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatusAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDAdminActionPerformed

    private void tabelLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelLaporanMouseClicked
        // TODO add your handling code here:
        //Ambil baris berapa yang diklik
        int baris = tabelLaporan.getSelectedRow();
        
        //Ambil model tabelnya
        DefaultTableModel model = (DefaultTableModel)tabelLaporan.getModel();
        
        //Ambil data dari baris itu, kolom per kolom
        String id = model.getValueAt(baris, 0).toString();
        String nama = model.getValueAt(baris, 1).toString();
        String deskripsi = model.getValueAt(baris, 3).toString();
        String status = model.getValueAt(baris, 4).toString();
        
        //Tempelkan data tersebut ke textfield dibawah
        txtIDAdmin.setText(id);
        txtNamaAdmin.setText(nama);
        txtDeskripsiAdmin.setText(deskripsi);
        cmbStatusAdmin.setSelectedItem(status); //otomatis memilih status sesuai di combobox
    }//GEN-LAST:event_tabelLaporanMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //Ambil data dari form inputan admin
        String id = txtIDAdmin.getText();
        String namaBaru = txtNamaAdmin.getText();
        String deskripsiBaru = txtDeskripsiAdmin.getText();
        String statusBaru = cmbStatusAdmin.getSelectedItem().toString();
        
        //cek apakah ada id yang dipilih
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih dahulu data pada tabel!");
            return;
        }
        
        try {
            Connection conn = KoneksiDB.configDB();
            //query sql update
            String sql = "UPDATE laporan SET nama_pelapor=?, deskripsi=?, status=? WHERE id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            //isi tanda tanya
            pst.setString(1, namaBaru);
            pst.setString(2, deskripsiBaru);
            pst.setString(3, statusBaru);
            pst.setString(4, id);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
            
            tampilkanData();
            bersihkanFormAdmin();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String id = txtIDAdmin.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih dahulu data yang akan dihapus pada tabel!");
            return;
        }
        
        //Menampilkan dialog konfirmasi ya/tidak
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Yakin ingin menghapus laporan ID: " + id + "?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION);
        //jika user pilih yes
        if (confirm == 0) {
            try {
                Connection conn = KoneksiDB.configDB();
                String sql = "DELETE FROM laporan WHERE id=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.execute();
                
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                
                // Refresh tabel dan bersihkan form
                tampilkanData();
                bersihkanFormAdmin();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
        tampilkanData();
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        tampilkanData();
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatusAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelLaporan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtDeskripsiAdmin;
    private javax.swing.JTextField txtIDAdmin;
    private javax.swing.JTextField txtNamaAdmin;
    // End of variables declaration//GEN-END:variables
    // Method khusus untuk mengambil data dari DB ke Tabel
    private void tampilkanData() {
        // 1. Siapkan header tabel
        String[] judulKolom = {"ID", "Pelapor", "Jenis", "Deskripsi", "Status", "Waktu Lapor"};
        DefaultTableModel model = new DefaultTableModel(null, judulKolom);
        tabelLaporan.setModel(model);

        try {
            Connection conn = KoneksiDB.configDB();
            Statement stm = conn.createStatement();
            
            // --- BAGIAN INI YANG BARU ---
            
            // Ambil kata kunci dari text field pencarian
            String keyword = txtCari.getText();
            
            String sql;
            // Cek: Jika kotak pencarian KOSONG, ambil semua data
            if (keyword.isEmpty()) {
                sql = "SELECT * FROM laporan ORDER BY id DESC";
            } 
            // Jika ada isinya, gunakan Filter WHERE LIKE
            else {
                // Simbol persen (%) artinya "cocokkan apa saja di depan/belakangnya"
                sql = "SELECT * FROM laporan WHERE nama_pelapor LIKE '%" + keyword + "%' OR deskripsi LIKE '%" + keyword + "%' ORDER BY id DESC";
            }
            
            // --- AKHIR BAGIAN BARU ---

            ResultSet res = stm.executeQuery(sql);

            // Looping data (sama seperti sebelumnya)
            while (res.next()) {
                Vector baris = new Vector();
                baris.add(res.getInt("id"));
                baris.add(res.getString("nama_pelapor"));
                baris.add(res.getString("jenis_laporan"));
                baris.add(res.getString("deskripsi"));
                baris.add(res.getString("status"));
                baris.add(res.getString("tanggal_input")); 
                model.addRow(baris);
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data:\n" + e.getMessage());
        }
    }
    private void bersihkanFormAdmin() {
        txtIDAdmin.setText("");
        txtNamaAdmin.setText("");
        txtDeskripsiAdmin.setText("");
        cmbStatusAdmin.setSelectedIndex(0);
    }
    
}
