/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class FormLaporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLaporan.class.getName());

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        btnKirim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pelapor");

        txtNama.setForeground(new java.awt.Color(153, 153, 153));
        txtNama.setText("Masukkan Nama Anda");
        txtNama.setToolTipText("");
        txtNama.addActionListener(this::txtNamaActionPerformed);

        jLabel2.setText("Jenis Laporan");

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barang Hilang", "Fasilitas Rusak" }));

        jLabel3.setText("Deskripsi Masalah");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setForeground(new java.awt.Color(153, 153, 153));
        txtDeskripsi.setRows(5);
        txtDeskripsi.setText("Jelaskan detail laporan...\n");
        jScrollPane1.setViewportView(txtDeskripsi);

        btnKirim.setBackground(new java.awt.Color(51, 153, 255));
        btnKirim.setText("Kirim Laporan");
        btnKirim.addActionListener(this::btnKirimActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKirim)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(54, 54, 54)
                            .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addComponent(txtNama)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnKirim)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        // 1. Ambil data dari form GUI
        String nama = txtNama.getText();
        String jenis = cmbJenis.getSelectedItem().toString();
        String deskripsi = txtDeskripsi.getText();
        
        // 2. Validasi (Cek kosong)
        if (nama.isEmpty() || deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi Nama dan Deskripsi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Stop, jangan lanjut ke bawah
        }
        
        // 3. Proses Simpan ke Database
        try {
            // Kueri SQL untuk menyimpan data
            // Tanda tanya (?) adalah placeholder yang akan diisi nanti
            String sql = "INSERT INTO laporan (nama_pelapor, jenis_laporan, deskripsi) VALUES (?, ?, ?)";
            
            // Panggil koneksi dari file KoneksiDB.java yang tadi dibuat
            Connection conn = KoneksiDB.configDB();
            
            // Siapkan statement
            PreparedStatement pst = conn.prepareStatement(sql);
            
            // Isi tanda tanya (?) dengan data dari variabel
            pst.setString(1, nama);      // ? pertama diisi nama
            pst.setString(2, jenis);     // ? kedua diisi jenis
            pst.setString(3, deskripsi); // ? ketiga diisi deskripsi
            
            // Eksekusi perintah SQL
            pst.execute();
            
            // Jika berhasil sampai sini, berarti data tersimpan
            JOptionPane.showMessageDialog(this, "Laporan Berhasil Disimpan ke Database!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            // Bersihkan form
            txtNama.setText("");
            txtDeskripsi.setText("");
            cmbJenis.setSelectedIndex(0);
            
        } catch (Exception e) {
            // Jika ada error saat proses database
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Laporan:\n" + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKirimActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLaporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKirim;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
